
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE shift2bikes_events (composite_event_id TEXT PRIMARY KEY, id TEXT NOT NULL, title TEXT NOT NULL, lat REAL NOT NULL, lng REAL NOT NULL, address TEXT NOT NULL, audience TEXT NOT NULL, cancelled INTEGER NOT NULL, date TEXT NOT NULL, starttime TEXT NOT NULL, safetyplan INTEGER NOT NULL, details TEXT NOT NULL, venue TEXT NOT NULL, organizer TEXT NOT NULL, loopride INTEGER NOT NULL, shareable TEXT NOT NULL, endtime TEXT, email TEXT, eventduration INTEGER, image TEXT, locdetails TEXT, locend TEXT, newsflash TEXT, timedetails TEXT, webname TEXT, weburl TEXT, citycode TEXT NOT NULL, ridesource TEXT NOT NULL, source_data TEXT NOT NULL);
CREATE INDEX idx_citycode ON shift2bikes_events (citycode);
CREATE INDEX idx_date ON shift2bikes_events (date);
CREATE TABLE geocode_cache (location_key TEXT PRIMARY KEY, lat REAL NOT NULL, lng REAL NOT NULL, city TEXT NOT NULL, last_updated TEXT NOT NULL);
CREATE UNIQUE INDEX idx_geocode_key ON geocode_cache (location_key);
CREATE INDEX idx_geocode_city ON geocode_cache (city);
CREATE TABLE events (id INTEGER PRIMARY KEY, title TEXT NOT NULL, tinytitle TEXT, description TEXT NOT NULL, image_url TEXT, audience TEXT, ride_length TEXT, area TEXT, date_type TEXT, venue_name TEXT, address TEXT, location_details TEXT, ending_location TEXT, is_loop_ride INTEGER NOT NULL DEFAULT 0, city TEXT NOT NULL, organizer_name TEXT, organizer_email TEXT, organizer_phone TEXT, web_url TEXT, web_name TEXT, newsflash TEXT, hide_email INTEGER NOT NULL DEFAULT 0, hide_phone INTEGER NOT NULL DEFAULT 0, hide_contact_name INTEGER NOT NULL DEFAULT 0, group_code TEXT, edit_token TEXT UNIQUE, is_published INTEGER NOT NULL DEFAULT 0, is_featured INTEGER NOT NULL DEFAULT 0, moderation_notes TEXT, moderated_at TEXT, created_at TEXT NOT NULL DEFAULT (STRFTIME ('%Y-%m-%d %H:%M:%f', 'NOW')), updated_at TEXT NOT NULL DEFAULT (STRFTIME ('%Y-%m-%d %H:%M:%f', 'NOW')), latitude REAL, longitude REAL, image_uuid TEXT, FOREIGN KEY (group_code) REFERENCES ride_groups (code) ON DELETE SET NULL);
CREATE INDEX idx_published ON events (is_published);
CREATE INDEX idx_group_code ON events (group_code);
CREATE TABLE event_occurrences (id INTEGER PRIMARY KEY, event_id INTEGER NOT NULL, start_date TEXT NOT NULL, start_time TEXT NOT NULL, start_datetime TEXT NOT NULL, event_duration_minutes INTEGER, event_time_details TEXT, is_cancelled INTEGER NOT NULL DEFAULT 0, newsflash TEXT, FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE);
CREATE INDEX idx_occurrence_datetime ON event_occurrences (start_datetime);
CREATE INDEX idx_occurrence_event_id ON event_occurrences (event_id);
CREATE TABLE ride_groups (code TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, city TEXT, icon_url TEXT, is_active INTEGER NOT NULL DEFAULT 1, web_url TEXT, edit_token TEXT UNIQUE, created_at TEXT NOT NULL DEFAULT (STRFTIME ('%Y-%m-%d %H:%M:%f', 'NOW')), image_uuid TEXT, image_url TEXT);
CREATE INDEX idx_groups_edit_token ON ride_groups (edit_token);
CREATE TABLE submission_tokens (token TEXT PRIMARY KEY, city TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (STRFTIME ('%Y-%m-%d %H:%M:%f', 'NOW')), expires_at TEXT NOT NULL, used INTEGER NOT NULL DEFAULT 0);
CREATE INDEX idx_token_used ON submission_tokens (used);
CREATE INDEX idx_token_expiry ON submission_tokens (expires_at);
CREATE INDEX idx_events_image_uuid ON events (image_uuid);
CREATE INDEX idx_ride_groups_image_uuid ON ride_groups (image_uuid);
CREATE TABLE admin_api_keys (id INTEGER PRIMARY KEY AUTOINCREMENT, api_key TEXT UNIQUE NOT NULL, admin_name TEXT, created_at TEXT NOT NULL DEFAULT (STRFTIME ('%Y-%m-%d %H:%M:%f', 'NOW')), revoked_at TEXT, last_used_at TEXT);
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX idx_admin_api_keys_api_key ON admin_api_keys (api_key);
CREATE INDEX idx_admin_api_keys_revoked ON admin_api_keys (revoked_at);