environment:
  ENV: production
parameters: {}
packages:
  - name: api
    actions:
      - name: upcoming
        runtime: 'go:1.20'
        limits:
          timeout: 15000
        web: true
        environment:
          TURSO_DB_RO_TOKEN: "${TURSO_DB_RO_TOKEN}"
          TURSO_DB_URL: "${TURSO_DB_URL}"
      - name: past
        runtime: 'go:1.20'
        limits:
          timeout: 15000
        web: true
        environment:
          TURSO_DB_RO_TOKEN: "${TURSO_DB_RO_TOKEN}"
          TURSO_DB_URL: "${TURSO_DB_URL}"
  - name: scraperv2
    actions:
      - name: scraperv2
        runtime: 'go:1.20'
        limits:
          timeout: 300000
        environment: 
          TURSO_DB_RW_TOKEN: "${TURSO_DB_RW_TOKEN}"
          TURSO_DB_URL: "${TURSO_DB_URL}"
          GOOGLE_GEOCODING_API_KEY: "&{GOOGLE_GEOCODING_API_KEY}"
