
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE directory_analytics (id INTEGER PRIMARY KEY AUTOINCREMENT, source TEXT, clicked_cta INTEGER DEFAULT 0, pwa_clicked TEXT, request_headers TEXT, visited_at TEXT NOT NULL DEFAULT (STRFTIME ('%Y-%m-%d %H:%M:%f', 'NOW')), clicked_at TEXT);
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX idx_analytics_source ON directory_analytics (source);
CREATE INDEX idx_analytics_cta ON directory_analytics (clicked_cta);
CREATE INDEX idx_analytics_pwa ON directory_analytics (pwa_clicked);
CREATE INDEX idx_analytics_visited_at ON directory_analytics (visited_at);