
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE sync_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id TEXT NOT NULL, sync_type TEXT NOT NULL, status TEXT NOT NULL, error_msg TEXT, ride_count INTEGER DEFAULT 0, duration INTEGER DEFAULT 0, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, city_code TEXT, os TEXT DEFAULT 'Unknown');
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX idx_sync_logs_client_id ON sync_logs (client_id);
CREATE INDEX idx_sync_logs_timestamp ON sync_logs (timestamp);
CREATE INDEX idx_sync_logs_status ON sync_logs (status);
CREATE INDEX idx_sync_logs_city_code ON sync_logs (city_code);
CREATE TABLE client_errors (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id TEXT NOT NULL, error_type TEXT NOT NULL, error_msg TEXT NOT NULL, stack_trace TEXT, component TEXT, ACTION TEXT, url TEXT, user_agent TEXT, os TEXT DEFAULT 'Unknown', city_code TEXT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_client_errors_client_id ON client_errors (client_id);
CREATE INDEX idx_client_errors_timestamp ON client_errors (timestamp);
CREATE INDEX idx_client_errors_type ON client_errors (error_type);
CREATE INDEX idx_client_errors_component ON client_errors (component);
CREATE TABLE strava_api_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, endpoint TEXT NOT NULL, method TEXT NOT NULL, status_code INTEGER NOT NULL, response_time_ms INTEGER, rate_limit_15min_usage INTEGER, rate_limit_15min_limit INTEGER, rate_limit_daily_usage INTEGER, rate_limit_daily_limit INTEGER, read_limit_15min_usage INTEGER, read_limit_15min_limit INTEGER, read_limit_daily_usage INTEGER, read_limit_daily_limit INTEGER, message TEXT, clubs_count INTEGER, events_count INTEGER, athlete_id INTEGER);
CREATE INDEX idx_strava_status ON strava_api_logs (status_code);
CREATE INDEX idx_strava_endpoint ON strava_api_logs (endpoint);
CREATE INDEX idx_strava_created_at ON strava_api_logs (created_at);
CREATE INDEX idx_strava_athlete ON strava_api_logs (athlete_id);
CREATE INDEX idx_strava_rate_limit ON strava_api_logs (rate_limit_15min_usage, rate_limit_15min_limit);
CREATE INDEX idx_strava_read_limit ON strava_api_logs (read_limit_15min_usage, read_limit_15min_limit);